### PR TITLE
added build of dynamic libraries

### PR DESCRIPTION
**Pull request by fpom**

### CODE REVIEW

**Comment by yanntm** [comment]
what we need is a -enable-dynamic flag for configure that does not change flags of the static build.

**Comment by fpom** [comment]
Which binaries? Those in demo?

**Comment by yanntm** [comment]
ok I'll commit a patch addressing this soon, don't change all the files, we don't copy paste stuff like flags.

**Comment by fpom** [comment]
Sorry, I know nothing about autotools. I did my best to have things work...

**Comment by yanntm** [comment]
ok, so just pass `-enable-shared` to this version of libDDD to get a shared library.
Basically the macros in configure.ac disable shared by default, but it can be overriden by the user now.
You might get some "full static link is not possible in this context", I think they can be ignored.

**Comment by fpom** [comment]
Actually, using `-enable-shared`makes the compilation fail with

    make[2]: *** No rule to make target '../../ddd/libDDD.a', needed by 'hanoi_v1'.  Stop.
    make[2]: Leaving directory '/home/franck/work/tools/its/libDDD/demo/hanoi'

Which is not really a problem since its on the examples. But on the other hand, it does not build a `.so` library but only `.la`.

**Comment by yanntm** [comment]
yes, it's not quite working yet. 
I hope we won't have to copy/paste so much as your patch, but the -all-static in LDFLAGS blocks libtool from producing a .so.
I have an exam this afternoon, just use your version in the meantime, I'll write a cleaner patch with Alexandre's help. Same as you, each time I have to do autotools related stuff, it hurts, but it does work on all three win, linux and osx. The static flags are really necessary to get the end product tools to run on other machines without a dev environment.

**Pull request closed without merging**
